### ISSUE TITLE
How to install in on ubuntu?

### ISSUE THREAD

**Issue by navneetccna** [892768447/QFlat#3]
Please provide documentation to install on ubuntu.

I tried 
- pip install -i PyQt5Designer
- pip install -i https://pypi.doubanio.com/simple/PyQt5Designer

but getting error

ERROR: You must give at least one requirement to install (see "pip help install")

when i run python designer.py without PyQt5Designer getting following error

Traceback (most recent call last):
  File "designer.py", line 67, in <module>
    main()
  File "designer.py", line 63, in main
    raise Exception('Can not find designer')
Exception: Can not find designer

**Comment by 892768447** [comment]
So sorry, current project (designer tool) just for windows.
I will rewrite the project, and will provide tutorials.

**Comment by navneetccna** [comment]
Ok, thanks
